version: "3.8" # Specify the Docker Compose version

services:
  db:
    image: postgres:13 # Use the official PostgreSQL 13 image
    container_name: postgres_db # Name for the container
    environment:
      POSTGRES_DB: postgres # Default database name
      POSTGRES_USER: postgres # Default username
      POSTGRES_PASSWORD: postgres # Default password
    ports:
      - "5431:5432" # Map the container port to the host
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

volumes:
  postgres_data: # Named volume for persistent storage
